language: objective-c

before_install:
- gem install xcpretty
- gem install cocoapods -v '1.0.1'

env:
  global:
    - WORKSPACE=GEOSwift.xcworkspace
    - SCHEME=GEOSwift

matrix:
  include:
    - osx_image: xcode8
      env: SDK=iphonesimulator10.0 DESTINATION="OS=10.0,name=iPhone 6"
    - osx_image: xcode7.3
      env: SDK=iphonesimulator9.3 DESTINATION="OS=9.0,name=iPhone 6"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Release
    ONLY_ACTIVE_ARCH=YES
    ENABLE_TESTABILITY=YES
    clean test | xcpretty -c;
