language: objective-c
osx_image: xcode7.3

before_install:
  - gem install cocoapods -v '1.0.1'
script:
  - xctool clean build -workspace GEOSwift.xcworkspace -scheme GEOSwift  -destination 'platform=iOS Simulator,name=iPhone 6'
  - xctool test -workspace GEOSwift.xcworkspace -scheme GEOSwift  -destination 'platform=iOS Simulator,name=iPhone 6' -sdk iphonesimulator
